# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 06:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='default@gmail.com', max_length=254)),
                ('first', models.CharField(default='First', max_length=255)),
                ('last', models.CharField(default='Last', max_length=255)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('fields_of_expertise', django.contrib.postgres.fields.hstore.HStoreField()),
                ('account_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hours_taught', models.IntegerField(default=0)),
                ('ratingsArray', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=None)),
                ('avg_rating', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
