# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:45
from __future__ import unicode_literals

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fields_of_expertise',
            field=django.contrib.postgres.fields.hstore.HStoreField(null=True),
        ),
    ]
