# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20170916_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='account_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
