# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 05:47
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20170917_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='onlineBool',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='text',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(null=True), null=True, size=None),
        ),
    ]
