# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20170916_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hours_taught',
            field=models.IntegerField(default=0),
        ),
    ]
