# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_profile_hours_taught'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='ratingsArray',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), null=True, size=None),
        ),
    ]
