# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170916_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4, null=True),
        ),
    ]
